Algoritmo "base_para"

// Sintax / regra
// PARA variavel DE valor_inicial ATE valor_final [passo N] faca
// comando 1
// comando 2
// FIMPARA

Var

   i : inteiro

Inicio

   para i de 1 ate 5 faca
      escreval("Bom Dia")
   fimpara

   para i de 1 ate 5 faca
      escreval("Valor de i: ", i)
   fimpara
   
   para i de 5 ate 1 passo -1 faca
      escreval("Valor de i: ", i)
   fimpara
Fimalgoritmo